### PR TITLE
improvement: ability to align the label

### PR DESCRIPTION
**Pull request by LukeStonehm**
- added the ability to align the labels text widget as needed
- uses existing hardcoded values as defaults, therefore is fully backward compatible

### CODE REVIEW

**Comment by LukeStonehm** [comment]
Works nicely to have a combo of centered label, but left aligned text input

image
image

**Comment by Lzyct** [comment]
Hi @LukeStonehm , thanks for your PR. Could you update the README.md file also for the new parameter?

Thanks

**Comment by LukeStonehm** [comment]
@Lzyct it has been done

**Comment by Lzyct** [comment]
Cool, thanks @LukeStonehm

**Pull request merged**
